### ISSUE TITLE
Rectangular Query missing key schema element: hashkey

### ISSUE THREAD

**Issue by alpreu** [Sigm0oid/dynamodb-geo.py#41]
Hi, I'm trying to make a rectangular query as such:

```
QueryRectangleInput={
        "ExpressionAttributeNames": {
            "#n": "name"
        },
        "FilterExpression": "#n = :val1",
        "ExpressionAttributeValues": {
            ":val1": {"S": query},
        }
    }

    results = geoDataManager.queryRectangle(
        dynamodbgeo.QueryRectangleRequest(
                dynamodbgeo.GeoPoint(swLat, swLon),
                dynamodbgeo.GeoPoint(neLat, neLon),
                QueryRectangleInput
        )
    )
```

But am getting an error regarding the hashkey:
```
An error occurred (ValidationException) when calling the Query operation: Query condition missed key schema element: hashkey
Traceback (most recent call last):  File "/var/task/lambda_function.py", line 50, in lambda_handler    
results = geoDataManager.queryRectangle(  File "/opt/python/dynamodbgeo/GeoDataManager.py", line 49, in queryRectangle    results = self.dispatchQueries(covering, QueryRectangleInput)  File "/opt/python/dynamodbgeo/GeoDataManager.py", line 39, in dispatchQueries    results.extend(self.dynamoDBManager.queryGeohash(  File "/opt/python/dynamodbgeo/DynamoDBManager.py", line 37, in queryGeohash    response = self.config.dynamoDBClient.query(**params)  File "/opt/python/botocore/client.py", line 316, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/opt/python/botocore/client.py", line 635, in _make_api_call    raise error_class(parsed_response, operation_name) 
[ERROR] ClientError: An error occurred (ValidationException) when calling the Query operation: Query condition missed key schema element: hashkey Traceback (most recent call last):   File "/var/task/lambda_function.py", line 50, in lambda_handler     results = geoDataManager.queryRectangle(   File "/opt/python/dynamodbgeo/GeoDataManager.py", line 49, in queryRectangle     results = self.dispatchQueries(covering, QueryRectangleInput)   File "/opt/python/dynamodbgeo/GeoDataManager.py", line 39, in dispatchQueries     results.extend(self.dynamoDBManager.queryGeohash(   File "/opt/python/dynamodbgeo/DynamoDBManager.py", line 37, in queryGeohash     response = self.config.dynamoDBClient.query(**params)   File "/opt/python/botocore/client.py", line 316, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/opt/python/botocore/client.py", line 635, in _make_api_call     raise error_class(parsed_response, operation_name)
```

I took a look at the code and I believe the reason why it fails is because [here](https://github.com/Sigm0oid/dynamodb-geo.py/blob/1910368b020cddfe8275f94d7962cc48ca0ec9bd/dynamodbgeo/DynamoDBManager.py#L15) in the queryHash function of the DynamoDBManager the attribute name 'hashKey' is hardcoded, while I configured it as `config.hashKeyAttributeName = 'hashkey'`, so it is throwing because it cannot find 'hashkey' as 'hashKey' is being used I believe.

**Comment by Sigm0oid** [comment]
Hi alpreu,

Having a look ..
