### ISSUE TITLE
queryRectangle errors with AttributeError: 'dynamodb.ServiceResource' object has no attribute 'query'

### ISSUE THREAD

**Issue by utkarshdalal** [Sigm0oid/dynamodb-geo.py#44]
Hello,

I've successfully created a table in DynamoDB using this library, and have populated it with some data. When I'm trying to query it using queryRectangle, it errors out with `AttributeError: 'dynamodb.ServiceResource' object has no attribute 'query'`.

Here's my code:
```
import boto3
import dynamodbgeo
import traceback

dynamodb = boto3.resource('dynamodb')
bakeries_table = dynamodb.Table('bakeries')

config = dynamodbgeo.GeoDataManagerConfiguration(dynamodb, 'bakeries')
config.hashKeyLength = 9
config.rangeKeyAttributeName = 'bakery_id'
geoDataManager = dynamodbgeo.GeoDataManager(config)

QueryRectangleInput = {}

print(geoDataManager.queryRectangle(
    dynamodbgeo.QueryRectangleRequest(
        dynamodbgeo.GeoPoint(1.273452, 103.805550),
        dynamodbgeo.GeoPoint(1.321849, 103.840225), QueryRectangleInput)))
```

and here's the stacktrace:
```
ERROR - could not generate summary'dynamodb.ServiceResource' object has no attribute 'query' 
Traceback (most recent call last):
  File "get_bakeries/get_bakeries.py", line 31, in lambda_handler
    print(geoDataManager.queryRectangle(
  File "/Users/utkarshdalal/workspace/HoomiBackend/env/lib/python3.8/site-packages/dynamodbgeo/GeoDataManager.py", line 49, in queryRectangle
    results = self.dispatchQueries(covering, QueryRectangleInput)
  File "/Users/utkarshdalal/workspace/HoomiBackend/env/lib/python3.8/site-packages/dynamodbgeo/GeoDataManager.py", line 39, in dispatchQueries
    results.extend(self.dynamoDBManager.queryGeohash(
  File "/Users/utkarshdalal/workspace/HoomiBackend/env/lib/python3.8/site-packages/dynamodbgeo/DynamoDBManager.py", line 37, in queryGeohash
    response = self.config.dynamoDBClient.query(**params)
AttributeError: 'dynamodb.ServiceResource' object has no attribute 'query'
```

Help?

**Comment by utkarshdalal** [comment]
Ok I fixed this. I was using `boto3.resource` instead of `boto3.client`.
